
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTION ALPHA_VAL CARD_ID CHANGE_KEY COMMAND ITEM_ID NUMBER OF SUIT TO WITHS :  COMMAND US : COMMANDU : NUMBERU : ITEM_IDU : CARD_ID AU : CARD_IDU : CARD_ID TO PA : CARD_ID AA : BB : CARD_IDP : ACTIONP : ACTION CP : ACTION EC : CHANGE_KEY OF CARD_ID KC : CHANGE_KEY OF CARD_IDK : TO RR : NUMBERR : SUITR : ALPHA_VALE : F WITH FF : NUMBERF : CARD_ID'
    
_lr_action_items = {'COMMAND':([0,],[2,]),'$end':([1,2,3,4,5,6,7,8,10,11,12,13,14,15,17,19,22,23,24,26,27,28,29,],[0,-2,-1,-3,-4,-6,-10,-5,-9,-8,-7,-11,-12,-13,-22,-21,-15,-20,-14,-16,-17,-18,-19,]),'NUMBER':([2,13,21,25,],[4,19,19,27,]),'ITEM_ID':([2,],[5,]),'CARD_ID':([2,6,7,13,20,21,],[6,7,7,17,22,17,]),'TO':([6,22,],[9,25,]),'ACTION':([9,],[13,]),'CHANGE_KEY':([13,],[16,]),'OF':([16,],[20,]),'WITH':([17,18,19,],[-22,21,-21,]),'SUIT':([25,],[28,]),'ALPHA_VAL':([25,],[29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'U':([2,],[3,]),'A':([6,7,],[8,11,]),'B':([6,7,],[10,10,]),'P':([9,],[12,]),'C':([13,],[14,]),'E':([13,],[15,]),'F':([13,21,],[18,23,]),'K':([22,],[24,]),'R':([25,],[26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> COMMAND U','S',2,'p_s1','parser.py',19),
  ('S -> COMMAND','S',1,'p_s2','parser.py',24),
  ('U -> NUMBER','U',1,'p_u1','parser.py',29),
  ('U -> ITEM_ID','U',1,'p_u2','parser.py',34),
  ('U -> CARD_ID A','U',2,'p_u3','parser.py',39),
  ('U -> CARD_ID','U',1,'p_u4','parser.py',44),
  ('U -> CARD_ID TO P','U',3,'p_u5','parser.py',49),
  ('A -> CARD_ID A','A',2,'p_a1','parser.py',54),
  ('A -> B','A',1,'p_a2','parser.py',58),
  ('B -> CARD_ID','B',1,'p_b','parser.py',62),
  ('P -> ACTION','P',1,'p_p1','parser.py',66),
  ('P -> ACTION C','P',2,'p_p2','parser.py',71),
  ('P -> ACTION E','P',2,'p_p3','parser.py',76),
  ('C -> CHANGE_KEY OF CARD_ID K','C',4,'p_c1','parser.py',81),
  ('C -> CHANGE_KEY OF CARD_ID','C',3,'p_c2','parser.py',86),
  ('K -> TO R','K',2,'p_k','parser.py',91),
  ('R -> NUMBER','R',1,'p_r1','parser.py',96),
  ('R -> SUIT','R',1,'p_r2','parser.py',101),
  ('R -> ALPHA_VAL','R',1,'p_r3','parser.py',106),
  ('E -> F WITH F','E',3,'p_e','parser.py',111),
  ('F -> NUMBER','F',1,'p_f1','parser.py',116),
  ('F -> CARD_ID','F',1,'p_f2','parser.py',121),
]
