
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTION ALPHA_VAL CARD_ID CHANGE_KEY COMMAND ITEM_ID NUMBER OF SUIT TO WITHS :  COMMAND US : COMMANDU : NUMBERU : ITEM_IDU : CARD_ID UU : CARD_IDU : CARD_ID TO PP : ACTIONP : ACTION CP : ACTION EC : CHANGE_KEY OF CARD_ID KC : CHANGE_KEY OF CARD_IDK : TO RR : NUMBERR : SUITR : ALPHA_VALE : F WITH FF : NUMBERF : CARD_ID'
    
_lr_action_items = {'COMMAND':([0,],[2,]),'$end':([1,2,3,4,5,6,7,9,10,11,12,14,16,19,20,21,23,24,25,26,],[0,-2,-1,-3,-4,-6,-5,-7,-8,-9,-10,-19,-18,-12,-17,-11,-13,-14,-15,-16,]),'NUMBER':([2,6,10,18,22,],[4,4,16,16,24,]),'ITEM_ID':([2,6,],[5,5,]),'CARD_ID':([2,6,10,17,18,],[6,6,14,19,14,]),'TO':([6,19,],[8,22,]),'ACTION':([8,],[10,]),'CHANGE_KEY':([10,],[13,]),'OF':([13,],[17,]),'WITH':([14,15,16,],[-19,18,-18,]),'SUIT':([22,],[25,]),'ALPHA_VAL':([22,],[26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'U':([2,6,],[3,7,]),'P':([8,],[9,]),'C':([10,],[11,]),'E':([10,],[12,]),'F':([10,18,],[15,20,]),'K':([19,],[21,]),'R':([22,],[23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> COMMAND U','S',2,'p_s1','parser.py',19),
  ('S -> COMMAND','S',1,'p_s2','parser.py',23),
  ('U -> NUMBER','U',1,'p_u1','parser.py',27),
  ('U -> ITEM_ID','U',1,'p_u2','parser.py',31),
  ('U -> CARD_ID U','U',2,'p_u3','parser.py',35),
  ('U -> CARD_ID','U',1,'p_u4','parser.py',39),
  ('U -> CARD_ID TO P','U',3,'p_u5','parser.py',43),
  ('P -> ACTION','P',1,'p_p1','parser.py',47),
  ('P -> ACTION C','P',2,'p_p2','parser.py',51),
  ('P -> ACTION E','P',2,'p_p3','parser.py',55),
  ('C -> CHANGE_KEY OF CARD_ID K','C',4,'p_c1','parser.py',59),
  ('C -> CHANGE_KEY OF CARD_ID','C',3,'p_c2','parser.py',63),
  ('K -> TO R','K',2,'p_k','parser.py',67),
  ('R -> NUMBER','R',1,'p_r1','parser.py',71),
  ('R -> SUIT','R',1,'p_r2','parser.py',75),
  ('R -> ALPHA_VAL','R',1,'p_r3','parser.py',79),
  ('E -> F WITH F','E',3,'p_e','parser.py',83),
  ('F -> NUMBER','F',1,'p_f1','parser.py',87),
  ('F -> CARD_ID','F',1,'p_f2','parser.py',91),
]
